apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: verisphere-api-hpa
  namespace: verisphere
  labels:
    app: verisphere-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: verisphere-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Custom metrics (requires metrics server and custom metrics API)
  - type: Pods
    pods:
      metric:
        name: active_claims_per_pod
      target:
        type: AverageValue
        averageValue: "10"
  
  # External metrics (e.g., queue depth)
  - type: External
    external:
      metric:
        name: redis_queue_depth
        selector:
          matchLabels:
            queue: "verisphere-claims"
      target:
        type: Value
        value: "50"
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: verisphere-worker-hpa
  namespace: verisphere
  labels:
    app: verisphere-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: verisphere-worker
  minReplicas: 2
  maxReplicas: 50
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  
  # Queue depth metric
  - type: External
    external:
      metric:
        name: redis_queue_depth
        selector:
          matchLabels:
            queue: "verisphere-processing"
      target:
        type: Value
        value: "100"
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes
      policies:
      - type: Percent
        value: 20
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 10
        periodSeconds: 60
      selectPolicy: Max

---
# Vertical Pod Autoscaler (optional, requires VPA controller)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: verisphere-api-vpa
  namespace: verisphere
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: verisphere-api
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: verisphere-api
      minAllowed:
        cpu: 100m
        memory: 256Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]